name: First Workflow
on: push
jobs: 
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, Github Actions!'
  pwd-ls:
    name: PWD & LS
    runs-on: ubuntu-latest
    steps:
      - name: Print Wokring Directory
        run: pwd
      - run: ls -al
